name: Publish Dashboard Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard Project
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: mripta/dashboard:latest,mripta/dashboard:${{ github.event.release.tag_name }}
      - name: Docker Image Scan for Vulnerabilities
        uses: azure/container-scan@v0
        with:
          image-name: mripta/dashboard:latest
          severity-threshold: CRITICAL
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mripta/dashboard:latest,mripta/dashboard:${{ github.event.release.tag_name }}
      - name: Update Image Overview
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: mripta/dashboard
          description: Laravel dashboard used in the MRIPTA project
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}